server:
  port: 0
  forward-headers-strategy: framework

springdoc:
  swagger-ui:
    path: /doc/swagger-ui/index.html
  api-docs:
    path: /rutina/api-docs
  packages-to-scan: com.gym.rutina_service.controller

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${random.value}

spring:
  application:
    name: rutina-service
  flyway:
    enabled: true
    baseline-on-migrate: true
  jpa:
    show-sql: true
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  mvc:
    cors:
      mappings:
        "/**":
          allowed-origin-patterns: "*"
          allowed-methods: GET, POST, PUT, DELETE, PATCH, OPTIONS
          allowed-headers: "*"
          exposed-headers: "*"
          allow-credentials: false
          max-age: 3600

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: root
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/db_rutina_service_dev?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_rutina_service_test?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/db_rutina_service_prod?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: ''
  jpa:
    hibernate:
      ddl-auto: none
