server:
  port: 8080
  forward-headers-strategy: framework

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origin-patterns: "*"
                allowed-methods: "*"
                allowed-headers: "*"
                exposed-headers: "*"
                allow-credentials: false
                max-age: 3600

          routes:
            - id: pagos-service
              uri: lb://pago-service
              predicates:
                - Path=/api/v1/pagos/**, /pago/api-docs/**

            - id: metodos-pago-service
              uri: lb://pago-service
              predicates:
                - Path=/api/v1/metodos-pago/**, /metodos-pago/api-docs/**

            - id: rutinas-service
              uri: lb://rutina-service
              predicates:
                - Path=/api/v1/rutinas/**, /rutina/api-docs/**

            - id: ejercicios-service
              uri: lb://rutina-service
              predicates:
                - Path=/api/v1/ejercicios/**, /ejercicios/api-docs/**

            - id: rutina-ejercicios-service
              uri: lb://rutina-service
              predicates:
                - Path=/api/v1/rutina-ejercicios/**, /rutina-ejercicios/api-docs/**
            - id: socio-service
              uri: lb://socio-service
              predicates:
              - Path=/api/v1/socios/**, /api/v1/membresia/**, /socios/api-docs/**

            - id: actividad-service
              uri: lb://actividad-service
              predicates:
              - Path=/api/v1/entrenadores/**, /api/v1/clases/**, /api/v1/reservas/**, /actividad/api-docs/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: false

springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    urls:
      - name: Microservicio Pago
        url: /pago/api-docs
      - name: Microservicio Rutina
        url: /rutina/api-docs
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    enabled: true
